spring:
  profiles:
    active: development
  application:
    name: task-service-worker
queue:
  prefix: "task-service"
  creation: "creation"
  completion: "completion"
---
spring:
  profiles: development
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  port: 8081
---
spring:
  profiles: test
---